backend:
  name: git-gateway
  repo: Marcicano/Sabaai-Gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: "cursos"
    label: "Cursos na primeira pagina"
    folder: "/src/pages/cursos"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cursos-index"}
      - { label: "Nome do curso", name: "nomeCurso", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Cidades do Curso", name: "cidadeCurso", widget: "string" }
      - { label: "Data de Publicacao", name: "date", widget: "datetime" }
      - { label: "Publico Alvo", name: "publicoCurso", widget: "text" }
      - { label: "Sobre o Curso", name: "sobreCurso", widget: "text" }
      - { label: "Aula Abordagem", name: "abordagemCurso", widget: "text" }
      - { label: "Valor A Vista", name: "valorVista", widget: "string" }
      - { label: "Valor Parcelado", name: "valorParcelado", widget: "string" }
      