backend:
  name: git-gateway
  repo: Marcicano/Sabaai-Gatsby

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "cursos"
    label: "Cursos"
    folder: "/markdown/cursos"
    create: true
    slug: "{{slug}}"
    preview_path: "cursos/{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cursos-informacoes"}
      - { label: "Nome do Curso", name: "title", widget: "string" }
      - { label: "Image do Curso", name: "thumbnail", widget: "image" }
      - { label: "Posicao", name: "position", widget: "number" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cidades do Curso", name: "cidadeCurso", widget: "string" }
      - { label: "Publico Alvo", name: "publicoCurso", widget: "text" }
      - { label: "Sobre o Curso", name: "sobreCurso", widget: "text" }
      - { label: "Aula Abordagem", name: "abordagemCurso", widget: "text" }
      - { label: "Valor A Vista", name: "valorVista", widget: "string" }
      - { label: "Valor Parcelado", name: "valorParcelado", widget: "string" }

  - name: "infoindex"
    label: "Introducao Pagina Principal"
    folder: "/markdown/Intro"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Texto", name: "content", widget: "markdown" }
      - { label: "Curso", name: "title", widget: "hidden", default: "intro-primeira-pagina" }
      