backend:
  name: git-gateway
  repo: Marcicano/Sabaai-Gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: "cursos"
    label: "Cursos"
    folder: "/markdown/cursos"
    create: true
    slug: "{{slug}}"
    preview_path: "cursos/{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cursos-informacoes"}
      - { label: "Nome do Curso", name: "title", widget: "string" }
      - { label: "Image do Curso", name: "thumbnail", widget: "image" }
      - { label: "Posicao", name: "position", widget: "number" }
      - { label: "Data Publicacao", name: "date", widget: "datetime" }
      - { label: "Cidades do Curso", name: "cidadeCurso", widget: "string" }
      - { label: "body", name: "body", widget: "markdown" }

  - name: "professores"
    label: "Professores Pagina Principal"
    folder: "/markdown/Professores"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Professor Key", name: "professorKey", widget: "hidden", default: "professor-info" }
      - { label: "Nome do Professor", name: "title", widget: "string" }
      - { label: "Texto", name: "content", widget: "markdown" }    
      - { label: "Foto do Professor", name: "thumbnail", widget: "image" }


  - name: "viagem"
    identifier_field: body
    label: "Informacoes sobre Viagem"
    folder: "/markdown/Viagem"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Viagem Key", name: "viagemKey", widget: "hidden", default: "viagem-info" }
      - { label: "body", name: "body", widget: "markdown" }

  - name: "intro"
    identifier_field: body
    label: "Introducao Pagina Principal"
    folder: "/markdown/Intro"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-info" }
      - { label: "Texto", name: "texto", widget: "string", default: "Texto primeira pagina" }
      - { label: "body", name: "body", widget: "markdown" }

  
  - name: "agenda"
    label: "Agenda"
    folder: "/markdown/cidades"
    create: true
    slug: "{{slug}}"
    editor:
     preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cidades-informacoes"}
      - { label: "Nome da Cidade", name: "title", widget: "string" }
      - { label: "Texto Card", name: "textocard", widget: "string" }
      - { label: "Imagem Cidade", name: "thumbnail", widget: "image" }
      - {label: "Location", name: "location", widget: "map" }
      - { label: "body", name: "body", widget: "markdown" }


  
      
      
